// src/app/data.ts

export interface HiddenPlace {
  id: number;
  title: string;
  imageUrl: string;
  desc: string;
  lat: number;
  lng: number;
  district: string;
}

export const KERALA_SPOTS: HiddenPlace[] = [
  // --- 1. KASARAGOD DISTRICT ---
  { id: 1, district: "Kasaragod", title: "Ranipuram Misty Grasslands", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqSYrtNI6tySJyy-frZG-8Sx2_4QJXRQfYjg&s", desc: "Often called the 'Ooty of Kerala.' Hike through thick shola forests to reach massive, windswept green mountaintop meadows covered in rolling white fog.", lat: 12.4243, lng: 75.3564 },
  { id: 2, district: "Kasaragod", title: "Valiyaparamba Hidden Backwaters", imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/4f/81/e6/valiayaparmba-backwaters.jpg?w=1100&h=1100&s=1", desc: "A completely peaceful, non-commercial alternative to Alleppey. Surrounded by endless coconut groves and fed by four pristine coastal rivers.", lat: 12.1075, lng: 75.1485 },
  { id: 3, district: "Kasaragod", title: "Thaikadappuram Secluded Beach", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Fmobile%2Fthaikadappuram-beach-1720437580_5797fdf6cc63d064ec4a.webp&w=3840&q=75", desc: "A lonely, wide stretch of sand famous for its complete solitude and the rare Olive Ridley sea turtles that visit the quiet shores during late autumn.", lat: 12.2415, lng: 75.0942 },

  // --- 2. KANNUR DISTRICT ---
  { id: 4, district: "Kannur", title: "Kavvayi Island Mangrove Path", imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0c/d6/de/2b/you-can-either-opt-for.jpg?w=1200&h=-1&s=1", desc: "A stunning untouched backwater island stretch. Rent a small local wooden rowboat to navigate incredibly narrow mangrove walls during a quiet sunset.", lat: 12.0734, lng: 75.1952 },
  { id: 5, district: "Kannur", title: "Paithalmala Cloud Peak Trail", imageUrl: "https://www.dtpckannur.com/uploads/picture_gallery/gallery_images/paithalmala-trekking-1920x1080-20230414135222825468.jpg", desc: "The highest geographic peak in Kannur. A serene trek past the clouds to an observation tower looking over the dense forest borders.", lat: 12.0994, lng: 75.5562 },
  { id: 6, district: "Kannur", title: "Aralam Deep Sanctuary Track", imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/a4/f5/24/aralam-wildlife-sanctuary.jpg?w=1200&h=1200&s=1", desc: "The northernmost wildlife reserve in Kerala. Skip the crowded safari spots; hike alongside forest guards through true, unpolished rainforest pathways.", lat: 11.9362, lng: 75.8451 },

  // --- 3. WAYANAD DISTRICT ---
  { id: 7, district: "Wayanad", title: "Aranamala Peak Ridge", imageUrl: "https://cdn.tripuntold.com/media/photos/location/2020/09/24/eeaa2778-6b93-4110-bb7f-c1914cb0317f.jpg", desc: "A breathtaking, off-beat mountain ridge offering secluded views of the Western Ghats. Extremely misty and isolated, reached via a rugged jeep track.", lat: 11.5315, lng: 76.1124 },
  { id: 8, district: "Wayanad", title: "Kudukkathu Para Rock Hills", imageUrl: "https://keralapages.in/wp-content/uploads/Kudukkathu-Para-Rock-Formations.webp", desc: "Massive, under-visited rock formations surrounded by high grasslands. Exceptional for evening stargazing due to absolute zero light pollution.", lat: 11.6495, lng: 75.9521 },
  { id: 9, district: "Wayanad", title: "Pakshipathalam Ancient Rock Caves", imageUrl: "https://www.mywayanad.com/wp-content/uploads/2022/08/Pakshipathalam-4-Wayanad.jpg", desc: "Deep inside the Brahmagiri hills lies a maze of giant, primitive granite boulders hiding secret subterranean caves where wild mountain birds nest.", lat: 11.9312, lng: 75.9864 },

  // --- 4. KOZHIKODE DISTRICT ---
  { id: 10, district: "Kozhikode", title: "Thusharagiri Secret Cascade", imageUrl: "https://www.keralatourism.org/images/enchanting_kerala/large/thusharagiri_a_trekker_s_delight20161019051950_613_1.jpg", desc: "Deep inside the forest, past the main tourist areas, lies a secluded third-tier cascade pool surrounded by smooth granite boulders.", lat: 11.4722, lng: 76.0528 },
  { id: 11, district: "Kozhikode", title: "Vellarimala High Range Trail", imageUrl: "https://www.dtpckozhikode.com/uploads/picture_gallery/gallery_images/vellarimala-20230509172234418149.webp", desc: "A challenging mountain landscape characterized by raw rocky river beds, deep mountain drops, and intense mist cover along the Camel's Hump ridge.", lat: 11.4361, lng: 76.1404 },
  { id: 12, district: "Kozhikode", title: "Kadalundi Estuary Mangrove Loop", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Fvertical%2Faerial-view-of-kadalundi-bird-sanctuary-kozhikode-1738772731_ef0b9f2c02a6889b4a25.webp&w=3840&q=75", desc: "Where the Kadalundi River meets the Arabian Sea. Rent a tiny local canoe to slip through thousands of silent, wild mangrove island nodes.", lat: 11.1275, lng: 75.8294 },

  // --- 5. MALAPPURAM DISTRICT ---
  { id: 13, district: "Malappuram", title: "Mini Ooty Arimbra Hills", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Fmobile%2Fmini-ooty-glass-bridge-a-thrilling-experience-amidst-arimbra-hills-1727507072_350b28418dfcca0b15ca.webp&w=3840&q=75", desc: "A towering high-altitude ridge famous for its heavy rolling mist and deep stepped valley views. Follow the lower trails for true isolation.", lat: 11.1442, lng: 75.9814 },
  { id: 14, district: "Malappuram", title: "Nedumkayam Old Teak Reserve", imageUrl: "https://www.keralatourism.org/images/enchanting_kerala/large/nedumkayam_rainforest_unshackle_yourself_here20210910070921_1115_1.jpg", desc: "A peaceful forest area near Nilambur. Walk across a vintage hanging bridge over crystal clear woodland pools where wild deer often gather.", lat: 11.3145, lng: 76.3242 },
  { id: 15, district: "Malappuram", title: "Kodikuthimala Green Peak", imageUrl: "https://www.keralatourism.org/images/enchanting_kerala/large/kodikuthimala_malappuram20220207100430_1160_1.jpg", desc: "Often called the Ooty of Malappuram. A gentle mountain clearing with watchtowers and continuous cool winds sweeping over natural terraced rocks.", lat: 10.9822, lng: 76.3195 },

  // --- 6. PALAKKAD DISTRICT ---
  { id: 16, district: "Palakkad", title: "Kodiheri Riverside Meadow", imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/b7/55/15/near-water-falling-location.jpg?w=1200&h=-1&s=1", desc: "A pristine, wide green grass clearing right beside a sweeping river curve. Completely untouched and calm, perfect for peaceful evening contemplation.", lat: 10.8875, lng: 76.3151 },
  { id: 17, district: "Palakkad", title: "Silent Valley Rainforest Border", imageUrl: "https://www.keralatourism.org/ktadmin/img/pages/tablet/silent-valley-national-park-1721217742_f70793578057884756aa.webp", desc: "One of the last remaining undisturbed tropical rainforests in India. Pure, ancient wilderness paths filled with giant trees and rare wildlife.", lat: 11.1143, lng: 76.4292 },
  { id: 18, district: "Palakkad", title: "Nelliyampathy Orange Hill Country", imageUrl: "https://kfdcecotourism.com/storage/destination/6786481925754.jpg", desc: "A stunning mountain town flanked by old cloud-kissed tea estates, terraced orange orchards, and deep, breathtaking cliff drops.", lat: 10.5364, lng: 76.6941 },

  // --- 7. THRISSUR DISTRICT ---
  { id: 19, district: "Thrissur", title: "Chettuva Mangrove Island Loop", imageUrl: "https://media1.thrillophilia.com/filestore/8seyjrekk180tjafgmhcxkej4e08_1550744990_mangroves-in-chettuva.jpg.jpg", desc: "An incredible network of silent backwater canals weaving underneath wild mangroves. Discover hidden, serene, green water lanes.", lat: 10.5342, lng: 76.0411 },
  { id: 20, district: "Thrissur", title: "Marottichal Forest Pools", imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/ec/1e/3a/marottichal-waterfalls.jpg?w=700&h=400&s=1", desc: "An offbeat forest trek leading away from commercial lanes straight to open natural rock pools and seasonal jungle cascades.", lat: 10.4556, lng: 76.3624 },
  { id: 21, district: "Thrissur", title: "Chavakkar Beach Backwater Strip", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Ftablet%2Fmunakkal-beach-1727446307_75ac2226a3b239d9902f.webp&w=1920&q=75", desc: "A unique coastal anomaly where a completely silent backwater stream flows parallel to a completely deserted sandy ocean beach strip.", lat: 10.5942, lng: 76.0112 },

  // --- 8. ERNAKULAM DISTRICT ---
  { id: 22, district: "Ernakulam", title: "Bhoothathankettu Old Forest Trail", imageUrl: "https://www.keralatourism.org/images/eco-tourism/trekking_thumb/trekking-trails/_T2A5543_11072018171106.jpg", desc: "Skip the main dam gardens; cross the old structure to find a secret rugged walking trail twisting deep into a protected wilderness area.", lat: 10.1384, lng: 76.6661 },
  { id: 23, district: "Ernakulam", title: "Areekkal Hidden Cascades", imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/8d/3f/97/areekal-waterfalls-piramadam.jpg?w=1200&h=1200&s=1", desc: "A beautifully secluded, terraced waterfall hidden deep inside rubber plantations. The water falls smoothly over multiple rock steps.", lat: 9.9675, lng: 76.5028 },
  { id: 24, district: "Ernakulam", title: "Kadamakkudy Mangrove Channels", imageUrl: "https://www.dreamholidayskerala.com/blog/wp-content/uploads/2025/10/Kadamakudy-1024x683.jpg", desc: "A peaceful cluster of tiny islands on the outer edge of Cochin. Features endless views of traditional polders and narrow country boat lanes.", lat: 10.0494, lng: 76.2692 },
  { id: 43, district: "Ernakulam", title: "Paniyeli Poru River Rapids", imageUrl: "https://www.keralatourism.org/images/eco-tourism/trekking_thumb/trekking-trails/1_31082018055102.jpg", desc: "A raw, offbeat nature getaway where the Periyar River weaves through massive rocks and dense forest clusters. Famous for its pristine canopies and whispering natural rapids.", lat: 10.1381, lng: 76.6195 },
  { id: 44, district: "Ernakulam", title: "Thattekad Bird Sanctuary", imageUrl: "https://www.keralatourism.org/images/eco-tourism/trekking_thumb/jungle-safari/thattekkadu1_10072018171653.jpg", desc: "Designed by the legendary Salim Ali as the richest bird habitat in peninsular India. This dense evergreen forest patch on the banks of the Periyar is home to incredibly rare species.", lat: 10.1334, lng: 76.6934 },
  { id: 45, district: "Ernakulam", title: "Cherai Beach Backwaters", imageUrl: "https://keralabee.com/wp-content/uploads/2024/06/IMG_20240607_215953-1024x768.jpg", desc: "A beautiful 10-kilometer stretch of sand at the northern tip of Vypeen Island. Blends crashing waves of the Arabian Sea on one side with completely silent backwater canals on the other.", lat: 10.1441, lng: 76.1752 },
  { id: 46, district: "Ernakulam", title: "Fort Kochi Colonial Streets", imageUrl: "https://cf-images.assettype.com/thenewsminute/import/sites/default/files/Fort_Kochi_1.jpg?w=1200&h=900&auto=format%2Ccompress&fit=max&enlarge=true", desc: "A beautiful coastal walk lined with century-old colonial bungalows, huge rain trees, and iconic Chinese fishing nets. Perfect for exploring street art alleys, cafes, and watching harbor ships.", lat: 9.9694, lng: 76.2415 },

  // --- 9. IDUKKI DISTRICT ---
  { id: 25, district: "Idukki", title: "Kolukkumalai Eastern Sunrise Ridge", imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/32/20/9e/8c/caption.jpg?w=1200&h=1200&s=1", desc: "The highest organic tea estate in the world. Walk down the unpaved cliff trail at dawn to watch the cloud-bed valleys split open.", lat: 10.0242, lng: 77.2215 },
  { id: 26, district: "Idukki", title: "Anakkulam Wild Elephant Stream", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Fmobile%2Fanakulam-1743495823_0dc98908dd039e1fbd9f.webp&w=3840&q=75", desc: "A unique natural river clearing where herds of wild elephants regularly emerge from the dense reserve forest borders to drink mineral waters.", lat: 10.1645, lng: 76.9112 },
  { id: 27, district: "Idukki", title: "Urumbikkara Off-Road Cliff Peak", imageUrl: "https://keralabee.com/wp-content/uploads/2023/09/IMG_20230905_233331-jpg.webp", desc: "An incredible high-altitude plateau reachable only via unpaved rocky trails. Features abandoned estate buildings and endless green ridges.", lat: 9.5812, lng: 76.9145 },

  // --- 10. KOTTAYAM DISTRICT ---
  { id: 28, district: "Kottayam", title: "Illikkal Kallu Apex Monolith", imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/05/0d/74/scenic-paradise.jpg?w=1200&h=1200&s=1", desc: "A monumental 4000-foot split rock formation offering sweeping panoramic views across the Western Ghats peaks.", lat: 9.7554, lng: 76.8184 },
  { id: 29, district: "Kottayam", title: "Ilaveezha Poonchira Valley", imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/45/ae/a6/elaveezhapoonchira.jpg?w=900&h=-1&s=1", desc: "Meaning 'the valley where leaves don't fall.' A pristine, bowl-shaped green plateau sitting thousands of feet high with zero trees and endless horizons.", lat: 9.8145, lng: 76.7891 },
  { id: 30, district: "Kottayam", title: "Teekoy Spice Plantation Woods", imageUrl: "https://img.avianexperiences.com/attractions/5e54bc26-667e-4831-814d-686392e8ce3e", desc: "A quiet, low-altitude mountain valley town filled with dense clove, rubber, and vanilla plantations flanked by hidden stream networks.", lat: 9.7152, lng: 76.7112 },

  // --- 11. ALAPPUZHA DISTRICT ---
  { id: 31, district: "Alappuzha", title: "Kakkathuruthu Island of Crows", imageUrl: "https://www.keralatourism.org/images/newsbytes/large/kakkathuruthu_in_nat_geo_s_must_visit_list20161101050212_1868_1.jpg", desc: "A tiny, thin strip of land inside Vembanad Lake. Famous for quiet sunset vistas where traditional fishermen cast nets against golden skies.", lat: 9.8742, lng: 76.3404 },
  { id: 32, district: "Alappuzha", title: "Pathiramanal Secret Island Loop", imageUrl: "https://www.dtpcalappuzha.com/uploads/picture_gallery/gallery_images/pathiramanal-island-20230524133601418589.webp", desc: "A floating wilderness sanctuary in the middle of backwaters. Reachable only via country canoe, it acts as a quiet haven for migratory birds.", lat: 9.6151, lng: 76.3812 },
  { id: 33, district: "Alappuzha", title: "Thottappally Isolated Coast", imageUrl: "https://www.dtpcalappuzha.com/uploads/picture_gallery/gallery_images/thottapally-20230524151753106429.webp", desc: "Where the spillway system meets the open ocean. A dark-sand, dramatic beach boundary lined with coastal trees and completely free of vendors.", lat: 9.3112, lng: 76.3954 },

  // --- 12. PATHANAMTHITTA DISTRICT ---
  { id: 34, district: "Pathanamthitta", title: "Gavi Deep Evergreen Forest Route", imageUrl: "https://www.keralatourism.org/images/microsites/periyar/thekkady-1024x768.jpg", desc: "A strictly protected wilderness area inside reserve boundaries. Thick mossy roads, deep water reservoirs, and sightings of rare wildlife.", lat: 9.4352, lng: 77.1641 },
  { id: 35, district: "Pathanamthitta", title: "Chittar Lake Quiet Catchment", imageUrl: "https://gaviya.com/wp-content/uploads/2024/08/chittar-dam.jpg", desc: "A completely calm water reservoir hidden away behind thick rubber hills. Features crystal-clear shores and absolute quietude.", lat: 9.3151, lng: 76.8442 },
  { id: 36, district: "Pathanamthitta", title: "Charalkunnu Secluded Hill Station", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-CRToAt3j2a3vWZ2zhsuoDaC38-tOgOCWUQ&s", desc: "A tiny, low-profile hill clearing providing exceptional, peaceful panoramic views of the entire winding Pamba River valley below.", lat: 9.3812, lng: 76.7154 },

  // --- 13. KOLLAM DISTRICT ---
  { id: 37, district: "Kollam", title: "Munroe Island Mangrove Canoe Route", imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/03/a4/6c/2a/munroe-island-canoe-tours.jpg?w=1200&h=-1&s=1", desc: "A labyrinth of miniature canal networks weaving underneath wild mangroves. Hire a tiny hand-paddled canoe at dawn along quiet banks.", lat: 8.9842, lng: 76.6195 },
  { id: 38, district: "Kollam", title: "Rosemala Hidden Valley Overlook", imageUrl: "https://indiano.travel/wp-content/uploads/2024/11/Rosemala-View-Point-f.jpg", desc: "Deep inside the wildlife sanctuary, this viewpoint offers a magnificent bird's-eye view of water loops that look exactly like giant green rose petals.", lat: 8.9545, lng: 77.1182 },
  { id: 39, district: "Kollam", title: "Thenmala Ancient Shola Trails", imageUrl: "https://www.keralatourism.org/images/eco-tourism/destinations/sentharuni-wild-life-sanctuary.jpg", desc: "India's first planned eco-tourism zone. Deep forest walking paths, structural suspension bridges, and silent, moss-covered wilderness tracks.", lat: 8.9042, lng: 77.1011 },

  // --- 14. THIRUVANANTHAPURAM DISTRICT ---
  { id: 40, district: "Thiruvananthapuram", title: "Amboori Ashram Mountain Crest", imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/88/aa/7f/kurisumala-ashram.jpg?w=900&h=-1&s=1", desc: "A peaceful settlement bordered by deep water reservoirs and a monolithic rock pinnacle. Hidden entirely away from standard commercial travel routes.", lat: 8.4842, lng: 77.1812 },
  { id: 41, district: "Thiruvananthapuram", title: "Ponmudi Misty Hairpin Ridge", imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/75/e3/cd/ponmudi.jpg?w=900&h=500&s=1", desc: "Ascend past 22 dramatic mountain hairpin curves to find a stunning hill peak permanently blanketed by heavy rolling fog, wild orchids, and cold mountain winds.", lat: 8.7645, lng: 77.1112 },
  { id: 42, district: "Thiruvananthapuram", title: "Kappil Beach Estuary Overlook", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Ftablet%2Fkappil-beach-1727452074_793df661390d99a3fac2.webp&w=1920&q=75", desc: "A breathtaking coastal stretch where a high cliff ridge road separates the crashing waves of the Arabian Sea from the completely silent Edava Lake backwater logs.", lat: 8.7812, lng: 76.6842 },
  { id: 47, district: "Thiruvananthapuram", title: "Anchuthengu Mangrove Island", imageUrl: "https://www.keralatourism.org/images/microsites/varkala/varkala-1024x768.jpg", desc: "A historic coastal region holding a massive 17th-century British fort structure and a towering brick lighthouse. Rent a tiny country boat nearby to explore the hidden mangrove islands of the lagoon.", lat: 8.6752, lng: 76.7641 },
  { id: 48, district: "Thiruvananthapuram", title: "Bonacaud Abandoned Estate", imageUrl: "https://vargiskhan.com/log/wp-content/uploads/2020/09/bonacaud-5.jpg", desc: "The base station for the famous Agasthyarkoodam trek. Features sprawling old ruined tea factories, thick mist-covered valley clearings, and quiet forest streams.", lat: 8.7142, lng: 77.1852 },
  { id: 49, district: "Thiruvananthapuram", title: "Neyyar Dam Old Watch Tower", imageUrl: "https://media-cdn.tripadvisor.com/media/photo-s/07/3e/b8/28/neyyar-dam.jpg", desc: "Skip the standard garden walks and head toward the old forested lake boundaries. Surrounded by an elephant rehabilitation center and a deer sanctuary.", lat: 8.5241, lng: 77.1542 },
  { id: 50, district: "Thiruvananthapuram", title: "Varkala Cliff Black Sand Beach", imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/27/a5/18/ff/black-sand-beach.jpg?w=900&h=500&s=1", desc: "A majestic structural anomaly where tall, red tertiary sedimentary clay cliffs stand directly parallel to the Arabian Sea coast. Features clear views and unique beachside waters.", lat: 8.7364, lng: 76.7034 },

  // --- 15. EXPANSION ADDITIONS ---
  { id: 51, district: "Idukki", title: "Kallimali Viewpoint", imageUrl: "https://cdn.tripuntold.com/media/photos/location/2020/04/04/ecd6802f-a291-4465-96e8-2fe589ceb147.jpg", desc: "A breathtaking cliff-edge clearing offering an unmatched panoramic view over the vast Ponmudi reservoir waters and surrounding valleys.", lat: 9.9842, lng: 77.0514 },
  { id: 52, district: "Idukki", title: "Anayirankal Dam Meadows", imageUrl: "https://s7ap1.scene7.com/is/image/incredibleindia/2-anayirankal-munnar-kerala-attr-hero?qlt=82&ts=1726672869990", desc: "A sprawling blue water reservoir framed closely by dense green carpeted tea gardens and frequent visits by wild elephant herds coming down to bathe.", lat: 10.0125, lng: 77.1852 },
  { id: 53, district: "Idukki", title: "Thommankuthu Step Cascades", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Fmobile%2Fthommankuthu-waterfalls-1713949834_73157a8dc3645ca3808c.webp&w=3840&q=75", desc: "A unique seven-step terraced waterfall flowing deep through lush evergreen forest paths, creating a series of natural clear water swimming pools.", lat: 9.9542, lng: 76.8315 },
  { id: 54, district: "Wayanad", title: "Karapuzha Lake Banks", imageUrl: "https://www.gowayanad.info/images/karapuzhazipline.jpg", desc: "One of India's largest earth dams, featuring quiet, grassy banks and small lakeside inlets offering exceptional absolute silence away from high-range traffic.", lat: 11.6241, lng: 76.2295 },
  { id: 55, district: "Wayanad", title: "Cheengeri Rock Peak", imageUrl: "https://visit-wayanad.com/wp-content/uploads/2024/10/cheengeri-hills-trekking.jpg", desc: "An incredible adventure-focused rock monolith trek that opens up into a sweeping 360-degree high-angle view over the entire misty Wayanad plateau.", lat: 11.6364, lng: 76.2482 },
  { id: 56, district: "Wayanad", title: "Kuruva Deep River Islands", imageUrl: "https://www.dtpcwayanad.com/uploads/picture_gallery/gallery_images/kuruva-island-wayanad-24-20230429182424616090.webp", desc: "A sprawling, unique cluster of isolated mangrove river delta islands on the Kabini River, accessible via traditional hand-tied bamboo rafts.", lat: 11.8212, lng: 76.0914 },
  { id: 57, district: "Ernakulam", title: "Inchathotty Hanging Bridge", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Ftablet%2Finchathotty-suspension-bridge-ernakulam-69077d0353webp-20260325234847346586.webp&w=1920&q=75", desc: "The longest suspension footpath bridge in Kerala. Walks directly over the wide roaring Periyar river rapids into a peaceful woodland clearing.", lat: 10.1342, lng: 76.8214 },
  { id: 58, district: "Ernakulam", title: "Ezhattumugham Nature Village", imageUrl: "https://media.assettype.com/outlooktraveller/2025-01-10/vlxo4g0v/shutterstock1672132948.jpg?w=1200&auto=format%2Ccompress&fit=max&format=webp&dpr=1.0", desc: "A beautiful riverside nature park where the Chalakudy River splits smoothly into seven narrow streams trickling past massive rocks and green canopies.", lat: 10.2312, lng: 76.4641 },
  { id: 59, district: "Kottayam", title: "Aruvikkachal Forest Falls", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Aruvickachal_Water_Falls.jpg/1280px-Aruvickachal_Water_Falls.jpg", desc: "A completely unpolished, hidden 200-foot jungle cascade dropping straight down into a deep, steep rubber plantation valley.", lat: 9.6842, lng: 76.8115 },
  { id: 60, district: "Kottayam", title: "Marmala Secret Cascade", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Fmobile%2Fmarmala-stream-kottayam-1727678294_8928c5f4b080ae547b43.webp&w=3840&q=75", desc: "Deep within a network of isolated estate trails lies a powerful, hidden waterfall roaring down into a natural granite basin rock cavity.", lat: 9.7214, lng: 76.8441 },
  { id: 61, district: "Palakkad", title: "Dhoni Forest Trek", imageUrl: "https://www.keralatourism.org/images/eco-tourism/trekking_thumb/trekking-trails/DSC_2145_09072018171909.jpg", desc: "A quiet, highly protected 3-hour hillside forest walk alongside mountain streams leading straight to a beautiful, clear jungle waterfall pool.", lat: 10.8415, lng: 76.6324 },
  { id: 62, district: "Palakkad", title: "Kava Lake Basin Lookout", imageUrl: "https://www.dtpcpalakkad.com/uploads/picture_gallery/gallery_images/kava-palakkad-4-20230131231600534047.webp", desc: "Often called the birthplace of the monsoon cloud front. A spectacular reservoir clearing framed closely by giant jagged mountain peaks.", lat: 10.8354, lng: 76.6892 },
  { id: 63, district: "Thrissur", title: "Peechi Forest Catchment", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Fmobile%2Fpeechi-vazhani-wildlife-sanctuary-1721055340_97f207b638b39a159697.webp&w=3840&q=75", desc: "An expansive woodland water reservoir reserve that plays host to quiet country boat safaris and glimpses of wild forest life along the banks.", lat: 10.5312, lng: 76.3814 },
  { id: 64, district: "Thrissur", title: "Asurankundu Secluded Dam", imageUrl: "https://www.premclt.com/uploads/9/1/5/9/9159993/3946395_orig.jpg", desc: "A completely offbeat reservoir hidden deep inside a dense forest strip. Features an absolute zero noise footprint and beautiful green horizons.", lat: 10.6942, lng: 76.2915 },
  { id: 65, district: "Malappuram", title: "Nilambur Conolly Teak Plot", imageUrl: "https://www.keralatourism.org/images/enchanting_kerala/hri/Conolly_s_Plot_Malappuram_1445.jpg", desc: "The oldest man-made teak plantation in the world, home to giant historic trees and a beautiful hanging bridge crossing the Chaliyar River.", lat: 11.2742, lng: 76.2115 },
  { id: 66, district: "Kozhikode", title: "Kariathumpara Green Valley", imageUrl: "https://www.keralatourism.org/ktadmin/img/pages/tablet/kariyathumpara-1743496214_ee8c3d7f5b34a1ce9cd5.webp", desc: "Often referred to as the 'Maldives of Malabar.' Rolling green grass meadows directly flanking crystal-clear, shallow freshwater streams.", lat: 11.5312, lng: 75.9242 },
  { id: 67, district: "Kozhikode", title: "Kakkayam Dam Cliff Tracks", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Fmobile%2Fkakkayam-1723551576_74856857973f8e766d64.webp&w=3840&q=75", desc: "A deep mountain valley reservoir surrounded by sheer rocky cliffs, secret side cascades, and excellent, cold high-range winds.", lat: 11.5542, lng: 75.9315 },
  { id: 68, district: "Kannur", title: "Madayipara Ancient Plateau", imageUrl: "https://www.keralatourism.org/images/ebooks/unexpected-destination/large/madayipara20170925061724.JPG", desc: "A magnificent laterite hill plateau that completely changes colors with the seasons—shifting from a lush blue-flower bed into golden-brown plains.", lat: 12.0315, lng: 75.2954 },
  { id: 69, district: "Kannur", title: "Ezhimala Isolated Promontory", imageUrl: "https://cdn.tripuntold.com/media/photos/location/2018/08/14/98a60650-d681-46a5-b9cb-ec6fb106df99.jpg", desc: "A historic coastal high hill group standing directly over the blue Arabian sea coast, featuring wild coastal shrubs and completely empty beach sands.", lat: 12.0164, lng: 75.2012 },
  { id: 70, district: "Kasaragod", title: "Ananthapura Lake Temple Rock", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Ftablet%2Fananthapura-lake-temple-kasaragod-1727186376_2a431800c2cf7cc8e98e.webp&w=1920&q=75", desc: "An incredible ancient structure sitting directly in the center of a rectangular mirror-like spring lake fed by natural mountain aquifers.", lat: 12.5842, lng: 74.9814 },
  { id: 71, district: "Alappuzha", title: "Andhakaranazhi Coastal Inlet", imageUrl: "https://sun-b2b.s3.us-east-2.amazonaws.com/attraction/2021-05-21things12-14-06.jpg", desc: "A dramatic coastal anomaly where backwater lagoon channels directly meet the crashing surf of the open ocean coast past a quiet lighthouse.", lat: 9.7415, lng: 76.2842 },
  { id: 72, district: "Pathanamthitta", title: "Perunthenaruvi Honey Cascades", imageUrl: "https://www.keralatourism.org/images/enchanting_kerala/hri/The_Charm_of_Perunthenaruvi_1316.jpg", desc: "A broad, powerful waterfall dropping into a vast rocky gorge cavity along the Pamba River line, known for its deep rock shelf configurations.", lat: 9.4124, lng: 76.8812 },
  { id: 73, district: "Kollam", title: "Jatayu Earth Center Ridge", imageUrl: "https://www.keralatourism.org/images/enchanting_kerala/large/jatayu_earth_s_centre_kerala_s_latest_addiction20181008064850_848_1.jpg", desc: "The largest functional bird sculpture in the world, sitting majestically on top of a massive monolithic hill ridge looking out over endless countryside.", lat: 8.8642, lng: 76.8674 },
  { id: 74, district: "Thiruvananthapuram", title: "Madavoorpara Rock Cave Temple", imageUrl: "https://www.keralatourism.org/images/pages/images/madavoorpara_a_place_with_a_personality20180206102634_730_1.jpg", desc: "An ancient 8th-century rock-cut cave structure carved deep into a monumental mountaintop granite ridge, featuring a quiet bamboo park walking path.", lat: 8.5812, lng: 76.9114 },
  { id: 75, district: "Thiruvananthapuram", title: "Agasthyarkoodam Wilderness Peak", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Fmobile%2Fagasthyarkoodam-1707376316_f11b6043145b51c284d5.webp&w=3840&q=75", desc: "A massive structural mountain peak inside the Neyyar sanctuary boundary, blanketed by prehistoric mist forests and rare ancient medical herbs.", lat: 8.6142, lng: 77.1482 },
  { id: 76, district: "Ernakulam", title: "Mamalakandham Forest Trails", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Fmobile%2Fmamalakandam-ernakulam-c7ded5b57bwebp-20260325230753216991.webp&w=3840&q=75", desc: "A deep jungle hamlet bordered by rubber estates, elephant paths, and beautiful shallow streams running directly through old mountain clearings.", lat: 10.1584, lng: 76.8912 },
  { id: 77, district: "Idukki", title: "Calvary Mount Ridge Overlook", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Fvertical%2Fcalvary-mount-idukki-reservoir-inlets-and-forested-hill-slopes-42eae639aawebp-20260321105632313871.webp&w=3840&q=75", desc: "A dramatic, windswept ridge overlooking the deep blue Idukki reservoir catchment. Offers jaw-dropping geometric views of small islands down below.", lat: 9.8451, lng: 76.9524 },
  { id: 78, district: "Wayanad", title: "900 Kandi Sky Canopy Walk", imageUrl: "https://www.dtpcwayanad.com/uploads/picture_gallery/gallery_images/sky-park-1920-20250801100431503723.webp", desc: "A hidden deep-woods sanctuary inside a centuries-old plantation, famous for its structural glass bridge hanging directly over wild, steep valley canopies.", lat: 11.5341, lng: 76.1245 },
  { id: 79, district: "Pathanamthitta", title: "Konni Elephant Reserve Woods", imageUrl: "https://www.keralatourism.org/images/eco-tourism/destinations/Konni-elephent-camp.jpg", desc: "Cross the dynamic old timber yard to find a silent trekking layout looping underneath ancient teak nodes right along the Achankovil river banks.", lat: 9.2415, lng: 76.8452 },
  { id: 80, district: "Alappuzha", title: "Marari Hidden Shore Line", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Ftablet%2Fandhakaranazhi-beach-alappuzha-1728570389_69e5aac41e2ac4ba3b98.webp&w=1920&q=75", desc: "A sleepy fisherman's clearing completely untouched by commercial resort builds. Lined with giant bowing coconut trees and absolute quietude.", lat: 9.6012, lng: 76.2942 },
  { id: 81, district: "Kottayam", title: "Kumarakom Secret Lagoon Strip", imageUrl: "https://www.cghearth.com/uploads/uploadimage/20171120044751AMcoconut.jpg", desc: "Tucked inside the back boundary of the bird reserve sanctuary. Rent a non-commercial small country rowboat to slip beneath wild canopy nodes at dawn.", lat: 9.5942, lng: 76.4215 },
  { id: 82, district: "Thrissur", title: "Vazhani Dam Catchment Clearing", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Fmobile%2Fvazhani-dam-1730209392_542339daad7ecefaa0b6.webp&w=3840&q=75", desc: "Built entirely with structural clay, this pristine reservoir catchment features dramatic rolling mud cliffs and an empty horizontal green skyline.", lat: 10.6415, lng: 76.2812 },
  { id: 83, district: "Kollam", title: "Palaruvi High Drop Waterfalls", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Fmobile%2Fpalaruvi-waterfalls-1724427923_ad63ee28ee64a345db49.webp&w=3840&q=75", desc: "Meaning 'Stream of Milk.' A powerful, single-tier 300-foot natural white drop hitting a deep forest rock shelf basin enclosed by sheer stone cliffs.", lat: 8.9024, lng: 77.1641 },
  { id: 84, district: "Thiruvananthapuram", title: "Kurisumala Ashram Mist Summit", imageUrl: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgsAKlmbCgRBHdO6K2RH-GoVy-d83d20zGIWG7nadiK3YBVFxHujoPSxJiL2hrnI7WsLW1cYDK3KJ3TfoJqCIfl1kXHMDlQqBideRHWFBOHntJEHJ3qPkQCotFI4_qCkbWjGZB7GS2uQbkJ/s640/kurisumala_in_kottayam20131125151223_14_1.jpg", desc: "Ascend past steep pine forest slopes to reach a high-altitude monastery dairy farm permanently blanketed by dense fog and cold mountain breezes.", lat: 8.4912, lng: 77.1954 },
  { id: 85, district: "Malappuram", title: "Kottakkunnu Panoramic Garden Ridge", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Fmobile%2Fkottakkunnu-malappuram-1742121074_138033e69dd714f32d8c.webp&w=3840&q=75", desc: "A beautiful high hill fort plateau displaying ruined defensive structures, old stone retaining walls, and continuous cool evening winds.", lat: 11.0452, lng: 76.0694 },

  // --- 16. FINAL FRESH BATCH (COMPLETING 100+ MILESTONE) ---
  { id: 86, district: "Idukki", title: "Ramakkalmedu Windswept Peaks", imageUrl: "https://www.keralatourism.org/images/enchanting_kerala/large/windswept_heights_of_ramakkalmedu20150327114354_538_1.jpg", desc: "A high mountain summit legendary for having the strongest, non-stop winds in Asia. Offers views of sprawling agricultural plains out in Tamil Nadu.", lat: 9.8024, lng: 77.2415 },
  { id: 87, district: "Wayanad", title: "Banasura Sagar Earth Basin", imageUrl: "https://grassrootswayanad.in/blog/wp-content/uploads/2021/11/Banasura-Sagar-Dam-1-1024x576.jpeg", desc: "The largest earthen dam in India. Features isolated hill islands jutting straight out from pristine blue reservoir waters inside a cloud ring.", lat: 11.6294, lng: 75.9242 },
  { id: 88, district: "Pathanamthitta", title: "Adavi Eco River Rapids", imageUrl: "https://www.keralatourism.org/images/eco-tourism/trekking_thumb/jungle-safari/adavi_16072018175921.jpg", desc: "A serene woodland stretch along the Kallar river line. Features slow coracle rowing paths weaving right underneath dense wild canopies.", lat: 9.2242, lng: 76.8912 },
  { id: 89, district: "Alappuzha", title: "Kottapuram Quiet Water Inlets", imageUrl: "https://www.keralatourism.org/uploads/muziris/picturegallery/mobile/kottappuram-waterfront-and-amphitheatre-in-kodungallur-thrissur-11082020163334.jpg", desc: "A non-commercial backwater layout hidden away from standard tourist boat streams, flanked exclusively by dense lines of marshy coastal palms.", lat: 10.1984, lng: 76.2115 },
  { id: 90, district: "Kottayam", title: "Vagamon Secret Pine Crest", imageUrl: "https://media.assettype.com/outlooktraveller/2025-09-29/2hl642f6/Vagamon?w=1200&auto=format%2Ccompress&fit=max&format=webp&dpr=1.0", desc: "A tall, isolated hill ridge entirely blanketed by towering pine stands. Features steep terrain tracks that stay wrapped in thick mist rows.", lat: 9.6842, lng: 76.9042 },
  { id: 91, district: "Thrissur", title: "Athirappilly Upper Forest Basin", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/81/The_View_of_the_Athirapally_Falls_during_the_onset_of_Monsoon.jpg", desc: "Skip the main crowded view tracks; head upward past rocky steps to discover massive, silent granite platforms where the river builds speeds.", lat: 10.2842, lng: 76.5562 },
  { id: 92, district: "Palakkad", title: "Malampuzha Jagged Peak Catchment", imageUrl: "https://images.alltrails.com/eyJidWNrZXQiOiJhc3NldHMuYWxsdHJhaWxzLmNvbSIsImtleSI6InVwbG9hZHMvcGhvdG8vaW1hZ2UvOTIwNTMzNDcvZjAzN2FiZWU2OTIyN2UxZjJlODRjM2U0NzMyNmRiZTcuanBnIiwiZWRpdHMiOnsidG9Gb3JtYXQiOiJ3ZWJwIiwicmVzaXplIjp7IndpZHRoIjoiNTAwIiwiaGVpZ2h0IjoiNTAwIiwiZml0IjoiaW5zaWRlIn0sInRvdGF0ZSI6bnVsbCwianBlZyI6eyJ0cmVsbGlzUXVhbnRpc2F0aW9uIjp0cnVlLCJvdmVyc2hvb3REZXJpbmdpbmciOnRydWUsIm9wdGltaXNlU2NhbnMiOnRydWUsInF1YW50aXNhdGlvblRhYmxlIjozfX19", desc: "A spectacular blue water horizon nestled closely inside the deep shadows of the monumental, raw Western Ghats mountain border.", lat: 10.8312, lng: 76.6812 },
  { id: 93, district: "Kozhikode", title: "Vayalada Mountain Peak Edge", imageUrl: "https://www.keralatourism.org/images/enchanting_kerala/hri/Vayalada_Kozhikode_1225.JPG", desc: "Often called the Gavi of Malabar. A dramatic cliffside viewpoint looking thousands of feet straight down into the deep blue Kakkayam reservoir lanes.", lat: 11.5342, lng: 75.8912 },
  { id: 94, district: "Kannur", title: "Palchuram High Pass Cascades", imageUrl: "https://www.trawell.in/admin/images/upload/210243696Palchuram-waterfall.jpg", desc: "A powerful four-tier waterfall falling through deep dense evergreen jungles right at the base of the winding high-range mountain pass road.", lat: 11.8842, lng: 75.9115 },
  { id: 95, district: "Kasaragod", title: "Bekal Hole Isolated Shore", imageUrl: "https://static2.tripoto.com/media/filter/tst/img/2012133/Image/1667881082_bekal_fort.jpg.webp", desc: "A wide, empty stretch of dark coastal sand wrapped underneath the giant historical laterite bastion walls of the old sea fort structure.", lat: 12.3942, lng: 75.0315 },
  { id: 96, district: "Idukki", title: "Meesapulimala High Mountain Track", imageUrl: "https://keralatrekking.in/wp-content/uploads/2025/04/A0406E1D-D072-42B7-BDF7-7A66DE1B0716-550x660.jpg", desc: "The second highest peak in the Western Ghats. A true wilderness hike past high rolling grasslands, rhododendron valleys, and dense fog nodes.", lat: 10.0984, lng: 77.1812 },
  { id: 97, district: "Wayanad", title: "Phantom Rock Monolith Node", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Phantom_Rock4.jpg", desc: "A striking, natural structural granite boulder formation shaped exactly like a human skull, sitting quietly above deep green estate valleys.", lat: 11.6112, lng: 76.2215 },
  { id: 98, district: "Ernakulam", title: "Kodanad River Banks", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Fmobile%2Fkodanad-elephant-training-centre-1724134377_8be40835604564a85ff1.webp&w=3840&q=75", desc: "A peaceful riverside clearing along the high edges of the Periyar, known for its deep woodland canopies and small, quiet country canoe paths.", lat: 10.1852, lng: 76.5342 },
  { id: 99, district: "Pathanamthitta", title: "Kakki Blue Water Reservoir", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Ftablet%2Fkakki-dam-1727450806_d58e78602186169a24c6.webp&w=1920&q=75", desc: "An expansive mountain lake hidden entirely away behind deep reserve boundaries. Features dense, moss-covered roads and occasional wild elephant viewings.", lat: 9.3242, lng: 77.1415 },
  { id: 100, district: "Alappuzha", title: "Punnapra Secluded Beach Strip", imageUrl: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=60", desc: "A long, quiet stretch of clean sand completely free of vendors and tourist shops, known for its beautiful wide horizons and peaceful coastal winds.", lat: 9.4452, lng: 76.3212 },
  { id: 101, district: "Thrissur", title: "Chimmini Jungle Sanctuary Track", imageUrl: "https://www.keralatourism.org/images/eco-tourism/prg-inner/photo2.jpg", desc: "Walk past the main guard structures to discover rugged unpolished pathways cutting right inside deep dense tropical rainforest formations.", lat: 10.4415, lng: 76.4694 },
  { id: 102, district: "Palakkad", title: "Siruvani River Catchment Platform", imageUrl: "https://th-i.thgim.com/public/incoming/jmytk8/article67206500.ece/alternates/FREE_1200/CB21_Siruvani.jpg", desc: "A magnificent deep forest water channel hidden beneath giant trees, celebrated for having some of the cleanest drinking water aquifers in the world.", lat: 10.9542, lng: 76.6842 },
  { id: 103, district: "Kozhikode", title: "Janakikadu Eco Protected Trail", imageUrl: "https://www.keralatourism.org/_next/image/?url=http%3A%2F%2F127.0.0.1%2Fktadmin%2Fimg%2Fpages%2Fmobile%2Fjanakikad-kozhikode-1722333464_5b3ae1cd3e38f02e43b5.webp&w=3840&q=75", desc: "A fully shaded, peaceful forest track cutting cleanly underneath a vast thick canopy architecture of rare medicinal trees and wild bird nesting clearings.", lat: 11.5942, lng: 75.8112 },
  { id: 104, district: "Kasaragod", title: "Kottancheri High Grass Valley", imageUrl: "https://www.keralatourism.org/images/ebooks/unexpected-destination/large/kottancherry_hills20170925061710.jpg", desc: "A beautiful mountain clearing that looks exactly like a miniature version of Munnar, completely hidden inside the northernmost hill ranges.", lat: 12.3912, lng: 75.4215 },
  { id: 105, district: "Idukki", title: "Anamudi Shola Moss Woods", imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/de/cd/e1/anamudi-shola-national.jpg?w=1200&h=-1&s=1", desc: "A unique, strictly protected high-altitude cloud rainforest where giant primeval trees are completely covered in thick ancient moss layers.", lat: 10.1512, lng: 77.1954 },
  { id: 106, district: "Wayanad", title: "Lakkidi High Pass Viewpoint", imageUrl: "https://thewoodsresorts.com/uploads/media/lakkidi-view-point-in-wayanad6605af9feaece.webp", desc: "One of the highest locations in Wayanad, offering a bird's-eye view looking straight down at the nine dramatic mountain hairpin curves weaving up the cliff.", lat: 11.5114, lng: 76.0112 },
  { id: 107, district: "Ernakulam", title: "Mulavukad Sea Basin Walk", imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/94/32/ee/mulavukad-island.jpg?w=900&h=500&s=1", desc: "A beautiful coastal pathway on the quiet edge of the island, providing clean panoramic views of the wide shipping lanes and shifting harbor vessels.", lat: 9.9942, lng: 76.2842 },
  { id: 108, district: "Kottayam", title: "Nattakom Rubber Woods Track", imageUrl: "https://kumarakom.com/uploads/post_photos/4188b67ebfaf8fad9d3fcfbee5b01afd.jpg", desc: "A quiet, fully shaded network of walking paths cutting through deep, rows of rubber plantations flanked by small natural water canals.", lat: 9.5562, lng: 76.5342 },
  { id: 109, district: "Pathanamthitta", title: "Moozhiyar Dam Mountain Pass", imageUrl: "https://www.keralatourism.org/images/enchanting_kerala/hri/Moozhiyar_Dam_An_Engineering_Marvel_1389.jpg", desc: "Deep inside protected reserve ecosystems, this quiet reservoir features incredibly narrow roads tracking alongside sweeping valley drop-offs.", lat: 9.2842, lng: 77.0694 }
];
